### PR TITLE
Support for the definition of new Crs.

### PR DESCRIPTION
**Pull request by chiccorusso**
Hi. This change is for the definition of new CRS to be used in a Map.

One can use existing CRS with Crs.byName() and define and use new CRS with Crs.add().

### CODE REVIEW

**Comment by mstahv** [comment]
Looks good to me, thanks!

**Comment by mstahv** [comment]
You seem to have quite old fork. Could you apply the change on the latest master from my branch or are you tied to the old Leaflet 0.7 series ?

**Comment by chiccorusso** [comment]
Hello Matti.
Yes, I need to use Leaflet-Draw and Leaflet-Shramov so, as far as I can understand, I can't update to the 1.0.0 series. Or can I?

I'm adding some documentation.

**Comment by mstahv** [comment]
v-leaflet-shramov is already upgraded to 1.0, but I guess v-leaflet-draw is till in 0.7 era. To release another 0.7 version, I'd need to create a separate branch and pull this there :-(

Have you followed Leaflet.Draw development lately? Is it ready for 1.0 series? Maybe it would be easier just to update that as well. I have personally used the v-leaflet-editable lately instead of v-leaflet-draw.

**Comment by mstahv** [comment]
Leaflet.Draw has a 1.0 branch:
https://github.com/Leaflet/Leaflet.draw/commits/leaflet-master

I'll give its update a shot.

**Comment by chiccorusso** [comment]
Nice! I'll try. I didn't notice.

Thank-you.

**Comment by mstahv** [comment]
I quickly tried to do a conversion, but for example closing polygons or polylines don't seem to work.

**Comment by mstahv** [comment]
Not sure if it is an issue in the wrapper or Leaflet.draw itself

**Comment by mstahv** [comment]
Oops, I was bit too fast, I didn't update v-leaflet dependency yet...

**Comment by mstahv** [comment]
Yep, much more promising, some regressions. I'll see if I can tackle those easily.

**Pull request merged**
